name: Docker build and upload

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/README.yml'
      - 'LICENSE'
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/README.yml'
      - 'LICENSE'

jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 7
    strategy:
      fail-fast: false
      matrix:
        # linux/arm64, linux/armhf are not supported yet
        platform: [ linux/amd64 ]
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            finchsec/wifite2:latest
